Fixing MNIST dataloader
lava-nc/lava pull request #133
Opened 2021-11-30 14:23 UTC by tihbe

`tutorials/end_to_end/tutorial01_mnist_digit_classification.ipynb` doesn't work if you install lava with a `pip install` as `mnist.npy` is not packaged. I fixed it by completing these to-dos.

2021-11-30 16:54 UTC, mgkwill commented
@tihbe Thanks for the pull request!

We generally require an issue for each pull request describing the intent of the PR linked to the PR.

Beside that, it looks like you have a bandit security linting issue. Please run `bandit -r lava/ --format custom --msg-template` and fix the issue in question. Then I will assign some reviewers.

2021-11-30 17:11 UTC, tihbe commented
@mgkwill Thanks for the info ! Did you want me to create an issue for this PR first ?
I'm not 100% sure how to fix the security linter issue. It seems that using `urllib.request.urlopen` automatically triggers the linter. I've disabled the specific line triggering the error as suggested [here](https://stackoverflow.com/questions/48779202/audit-url-open-for-permitted-schemes-allowing-use-of-file-or-custom-schemes).

2021-11-30 18:07 UTC, mgkwill requested changes

2021-11-30 18:07 UTC, mgkwill commented on src/lava/utils/dataloader/mnist.py
> +                        f.write(res.read())
Despite the hardcoded URLs, I think you should validate that each starts with http or https before you pass to `urllib.request.urlopen(f"{mirror}{file}")`

2021-11-30 19:29 UTC, mgkwill requested changes

2021-11-30 19:29 UTC, mgkwill commented on src/lava/utils/dataloader/mnist.py
> +                    assert url.lower().startswith("http")
After python JITs the code asserts are removed. You will get a bandit security lint issue that references this.

Instead use an if/else with else throwing an `AssertError` that describes the fact that `url` does not start with 'http'

2021-11-30 19:30 UTC, mgkwill commented
Thanks for the updates @tihbe and trying to sort out the bandit security linting issues.

2021-12-03 09:02 UTC, srrisbud approved these changes

2021-12-03 09:06 UTC, srrisbud commented
@tihbe, have you addressed the change requested by @mgkwill?

2021-12-03 09:22 UTC, tihbe commented
@srrisbud Yes

2021-12-03 19:48 UTC, mgkwill approved these changes

2021-12-03 22:27 UTC, merged