Virtual ports on multiple incoming connections
lava-nc/lava pull request #224
Opened 2022-03-09 22:09 UTC by mathisrichter

Draft implementation to support virtual ports on multiple incoming connections of a port (wip).

Signed-off-by: Mathis Richter <mathis.richter@intel.com>

Issue Number: #223 

Objective of pull request: Support for virtual ports on multiple incoming connections to a Port.

## Pull request checklist

Your PR fulfills the following requirements:
- [x] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
- [ ] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
- [ ] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
- [ ] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
- [ ] Build tests (`pytest`) passes locally

## Pull request type

 

 

Please check your PR type:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe): 

## What is the current behavior?

-

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Supplemental information

2022-03-10 17:08 UTC, PhilippPlank requested changes
Looks good for me, I would just recommend to change the identifier of the csp_port dictionary.

2022-03-10 18:54 UTC, joyeshmishra commented on src/lava/magma/core/process/ports/ports.py
> +    return proc_name + "." + port_name
+1

2022-03-10 18:56 UTC, joyeshmishra approved these changes
Minor changes recommended.

2022-03-11 22:19 UTC, PhilippPlank approved these changes

2022-03-11 23:02 UTC, merged