Fix for dangling ports
lava-nc/lava pull request #274
Opened 2022-07-21 19:51 UTC by bamsumit

Issue Number: 246

Objective of pull request:

## Pull request checklist

Your PR fulfills the following requirements:
- [x] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
- [x] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
- [ ] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
- [x] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
- [x] Build tests (`pytest`) passes locally

## Pull request type

 

 

Please check your PR type:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe): 

## What is the current behavior?

- Dangling input/output port does not work.

## What is the new behavior?

- They work

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Supplemental information

2022-07-21 20:03 UTC, mathisrichter requested changes
Looks good, Sumit! It may be worth adding a dedicated unit test for this though to make sure this capability does not break in the future.

2022-07-21 20:05 UTC, bamsumit commented
> Looks good, Sumit! It may be worth adding a dedicated unit test for this though to make sure this capability does not break in the future.

Yeah I was looking at the best place to add that. I am not convinced it should go in `test_process.py` though. Suggestions?

2022-07-22 00:32 UTC, mathisrichter approved these changes
Nice! I think the unit test is fine there. Since it is a feature of the compiler, you could also have written it as a part of the Compiler tests and only tested the contents of the builders, for instance. But this is also nice, then we have a working example. :)

2022-07-22 00:32 UTC, mathisrichter commented on tests/lava/magma/runtime/test_io_ports.py
> +        # Reference h_var with var of the nested process
Missing full stop

2022-07-22 00:32 UTC, mathisrichter commented on tests/lava/magma/runtime/test_io_ports.py
> +        output not conected at all."""
conected -> connected

2022-07-22 14:00 UTC, PhilippPlank approved these changes

2022-07-22 16:12 UTC, merged

2022-07-22 16:12 UTC, mgkwill approved these changes