Messaging refactor develop
lava-nc/lava pull request #310
Opened 2022-08-15 10:26 UTC by hongdami

Issue Number: 

Objective of pull request:

## Pull request checklist

Your PR fulfills the following requirements:
- [ ] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
- [ ] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
- [ ] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
- [ ] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
- [ ] Build tests (`pytest`) passes locally

## Pull request type

 

 

Please check your PR type:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe): 

## What is the current behavior?

-

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Supplemental information

2022-08-16 02:04 UTC, killight98 requested changes

2022-08-16 02:04 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/multiprocessing.py
> +        self._smm: ty.Optional[SharedMemoryManager] = None
replace `SharedMemoryManager` by `SharedMemManager`.

2022-08-16 02:04 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/multiprocessing.py
> +        self._smm = SharedMemoryManager()
same with before.

2022-08-16 02:13 UTC, killight98 requested changes

2022-08-16 02:13 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/multiprocessing.py
> +            exit(0)
i think MultiProcessing/manager should handle the exit/stop.

2022-08-16 02:18 UTC, killight98 requested changes

2022-08-16 02:18 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/multiprocessing.py
> +class ProcessType(Enum):
mv this enum to pythonwrapper and bind the `ProcessType`

2022-08-16 02:18 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/multiprocessing.h
> +enum ChannelType {
rename as `ProcessType`？

2022-08-16 02:48 UTC, killight98 requested changes

2022-08-16 02:48 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/multiprocessing.py
> +    def actors(self):
get actors from actors_ at cpp

2022-08-16 02:48 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/multiprocessing.py
> +        self._actors: ty.List[Actor] = []
remove it.

2022-08-16 02:48 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/multiprocessing.py
> +    def smm(self):
same as `actors` func

2022-08-16 02:48 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/multiprocessing.py
> +        self._mp = CppMultiProcessing()
move to `__init__`

2022-08-17 01:44 UTC, killight98 requested changes

2022-08-17 01:44 UTC, killight98 commented on src/lava/magma/compiler/builders/channel_builder.py
> +from lava.magma.runtime.message_infrastructure.message_infrastructure \
from message_infrastructure.message_infrastructure_interface import (MessageInfrastructureInterface)

2022-08-17 01:44 UTC, killight98 commented on src/lava/magma/compiler/channels/pypychannel.py
> +        .message_infrastructure.message_infrastructure_interface \
same as before

2022-08-17 01:44 UTC, killight98 commented on src/lava/magma/runtime/runtime.py
> +from lava.magma.runtime.message_infrastructure.message_infrastructure \
same as before

2022-08-17 01:48 UTC, hongdami reviewed
1. update import path and __init__.py
2. fix typoerror
3. update bounded function to cpp
4. update pywrapper
5. add test for multiprocessing.py

2022-08-17 02:07 UTC, killight98 requested changes

2022-08-17 02:07 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/factory.py
> +from lava.magma.core.process.message_interface_enum import ActorType
porting ActorType

2022-08-17 02:07 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/factory.py
> +    .multiprocessing import MultiProcessing
change import

2022-08-17 03:01 UTC, killight98 approved these changes

2022-08-17 03:31 UTC, hexu33 approved these changes

2022-08-17 03:53 UTC, merged