MultiProcessing&Actor Implementation
lava-nc/lava pull request #321
Opened 2022-08-25 03:21 UTC by hongdami

Add Actor feature

Signed-off-by: Miao, Hongda <hongda.miao@intel.com>

Issue Number: 

Objective of pull request:

## Pull request checklist

Your PR fulfills the following requirements:
- [ ] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
- [ ] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
- [ ] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
- [ ] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
- [ ] Build tests (`pytest`) passes locally

## Pull request type

 

 

Please check your PR type:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe): 

## What is the current behavior?

-

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Supplemental information

2022-08-25 03:45 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/posix_actor.cc
> +  kill(pid_, SIGTERM);
we need to send `stop` cmd/signal to target actor, not kill.
maybe rename as `ForceStop`.

2022-08-29 02:39 UTC, killight98 commented on .github/workflows/ci-build.yml
> +      if: runner.os == 'Linux' || runner.os == 'macOS'
at current, `Linux` only

2022-08-29 02:41 UTC, killight98 requested changes

2022-08-29 02:41 UTC, killight98 commented on .github/workflows/ci-build.yml
> +        git lfs pull
don't need lfs?

2022-09-06 04:00 UTC, seowwj commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/message_infrastructure_py_wrapper.cc
> +    .def("stop", &PosixActor::Stop);
Do we need to add `force_stop` from `PosixActor::ForceStop`?

2022-09-06 07:52 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/CMakeLists.txt
> +                 OUTPUT_VARIABLE NUMPY_INCLUDE_DIR
u need to add `NUMPY_INCLUDE_DIR` into line 28 `target_include_directories`.
i think we could add getting `NUMPY_INCLUDE_DIR` at setup.py.

2022-09-07 01:22 UTC, killight98 approved these changes

2022-09-07 02:06 UTC, merged