DRAFT: Three Factor Learning
lava-nc/lava pull request #400
Opened 2022-10-07 21:33 UTC by bala-git9

Issue Number: 

Objective of pull request:
Implements the necessary changes to LAVA to support three factor learning rules. Contains a tutorial that implements a reward-modulated STDP learning rule. 

## Pull request checklist

Your PR fulfills the following requirements:
- [ ] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
- [ ] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
- [ ] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
- [ ] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
- [ ] Build tests (`pytest`) passes locally

## Pull request type

 

 

Please check your PR type:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe): 

## What is the current behavior?

-

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Supplemental information

2022-10-08 03:03 UTC, awintel requested changes
Looks good. Here's a little bit of feedback:

- Avoid language like "we", "our" if possible. Better to stay neutral. Not really clear who "we" is.
- Why "exposed in Lava"?
- Typo: "how to Implement a custom learning rule" -> lower case
- "using the Lava process libraries" There is only one Lava process library.
- Missing context what that means: "generate frozen patterns of activity"
- How did you choose which word to capitalize and which not: "Reward Modulated Spike-timing Dependent Plasticity (R-STDP) Learning rule"?
- Hebb is a person's name, so this should be upper case: "hebbian STDP"
- Rendering issue? 
![image](https://user-images.githubusercontent.com/68661711/194683754-4d8f75c8-4443-4505-ab9a-62fde9c87f99.png)
- "in a sum of product form as understood by Loihi's learning engine"?
- Same here? 
![image](https://user-images.githubusercontent.com/68661711/194683804-47d2a4cb-9656-4a4f-b6b4-bc256204e1bf.png)
- Same here: 
![image](https://user-images.githubusercontent.com/68661711/194683828-fef23273-659d-4219-8b06-0bca4a139231.png)
- I will not list every typo of the same kind anymore. Please check the whole tutorial including comments for inconsistent capitalization of words. Why"# High Reward decay constant", "# Epoch length", "#string learning rule for dt : ELIGIBILITY TRACE represented", "# String learning rule", "# Create custom LearningRule". I don't see a system here.
- If your t_epoch=2, then this statement is incorrect: "# The weights are updated at every-timestep"
- Would it help to give a short motivation how you choose magic number like "vth = 240"?
- Out of order: In the middle of the tutorial you suddenly define what LIF means "injecting spike trains to Leaky-Intergrate and Fire (LIF) neurons" although you have used LIF many times before.
- The circuit diagram is not fully explained: You are not associating pattern generators with the unfortunately named RingBuffers.What is BAP? Why is the yellow line labeled "Plastic"? The Synapses in the LearningDense Proc are plastic but not the connection between the synapses and the neurons. You explain the individual processes but not why they are wired the way they are.
- Don't we have a Loihi2SimCfg? We shouldn't be using a RunCfg that's called Loihi1SimCfg in a Loihi2 setup when Loihi1 is not even supported even if the behavior is the same between the two generations in this regard.
- Why do we need to post synaptic LIF neurons? One should be enough for this minimal test case. It just needs to be a LIF neuron that has the ability to accept regular feedforward input as well as a separate reward signal. Or are you somehow considering this as a two-compartment neuron?
- The tutorial just ends with "let's plot some results". There is no discussion of what's going on. How do the pre/post spikes and rewards signals related to the observed weight changes? Just like in a paper, we should say a few words what has been demonstrated and can be learned from the experiment/workload. Can we do anything interesting beyond this basic demonstration? Maybe vary some learning rule parameters and demonstrate what practical effects this has? You could encapsulate the basic setup and run function in a helper function that you can call with different control parameters such that it is easy to run the experiment several times, get more data and produce more interesting plots.

Thanks a lot!

2022-10-09 15:34 UTC, bala-git9 commented
Thank you @awintel for your feedback. It is still in an unpolished state. Thus, the DRAFT in the title. I will work on fixing those errors you mentioned. Very valuable and detailed. I appreciate it.

2022-10-10 02:42 UTC, bala-git9 commented
> Looks good. Here's a little bit of feedback:
> 
> * Avoid language like "we", "our" if possible. Better to stay neutral. Not really clear who "we" is.
> * Why "exposed in Lava"?
> * Typo: "how to Implement a custom learning rule" -> lower case
> * "using the Lava process libraries" There is only one Lava process library.
> * Missing context what that means: "generate frozen patterns of activity"
> * How did you choose which word to capitalize and which not: "Reward Modulated Spike-timing Dependent Plasticity (R-STDP) Learning rule"?
> * Hebb is a person's name, so this should be upper case: "hebbian STDP"
> * Rendering issue?
>   ![image](https://user-images.githubusercontent.com/68661711/194683754-4d8f75c8-4443-4505-ab9a-62fde9c87f99.png)
> * "in a sum of product form as understood by Loihi's learning engine"?
> * Same here?
>   ![image](https://user-images.githubusercontent.com/68661711/194683804-47d2a4cb-9656-4a4f-b6b4-bc256204e1bf.png)
> * Same here:
>   ![image](https://user-images.githubusercontent.com/68661711/194683828-fef23273-659d-4219-8b06-0bca4a139231.png)
> * I will not list every typo of the same kind anymore. Please check the whole tutorial including comments for inconsistent capitalization of words. Why"# High Reward decay constant", "# Epoch length", "#string learning rule for dt : ELIGIBILITY TRACE represented", "# String learning rule", "# Create custom LearningRule". I don't see a system here.
> * If your t_epoch=2, then this statement is incorrect: "# The weights are updated at every-timestep"
> * Would it help to give a short motivation how you choose magic number like "vth = 240"?
> * Out of order: In the middle of the tutorial you suddenly define what LIF means "injecting spike trains to Leaky-Intergrate and Fire (LIF) neurons" although you have used LIF many times before.
> * The circuit diagram is not fully explained: You are not associating pattern generators with the unfortunately named RingBuffers.What is BAP? Why is the yellow line labeled "Plastic"? The Synapses in the LearningDense Proc are plastic but not the connection between the synapses and the neurons. You explain the individual processes but not why they are wired the way they are.
> * Don't we have a Loihi2SimCfg? We shouldn't be using a RunCfg that's called Loihi1SimCfg in a Loihi2 setup when Loihi1 is not even supported even if the behavior is the same between the two generations in this regard.
> * Why do we need to post synaptic LIF neurons? One should be enough for this minimal test case. It just needs to be a LIF neuron that has the ability to accept regular feedforward input as well as a separate reward signal. Or are you somehow considering this as a two-compartment neuron?
> * The tutorial just ends with "let's plot some results". There is no discussion of what's going on. How do the pre/post spikes and rewards signals related to the observed weight changes? Just like in a paper, we should say a few words what has been demonstrated and can be learned from the experiment/workload. Can we do anything interesting beyond this basic demonstration? Maybe vary some learning rule parameters and demonstrate what practical effects this has? You could encapsulate the basic setup and run function in a helper function that you can call with different control parameters such that it is easy to run the experiment several times, get more data and produce more interesting plots.
> 
> Thanks a lot!

Fixed some of the text issues that was mentioned in your comment. Still working on polishing it further. But here are the answers to some of your questions. 

1.  Loihi2SimCfg has not been implemented yet. I will work fixing that. 
2. Yes, the idea of using two post-synaptic neurons is to change the reward trace for each neuron and show that the modulation of the plastic synapse is dependent on the reward signal. It will be evident once I include the output plot. I will add a couple of lines explaining the plots too. Still WIP. Will update tomorrow.

2022-10-10 17:06 UTC, awintel commented
> @awintel
> 
> Fixed some of the text issues that was mentioned in your comment. Still working on polishing it further. But here are the answers to some of your questions.
> 
> 1. Loihi2SimCfg has not been implemented yet. I think that needs to be updated. I can work on fixing that.
> 2. Yes, the idea of using two post-synaptic neurons is to change the reward trace for each neuron and show that the modulation of the plastic synapse is dependent on the reward signal. It will be evident once I include the output plot. I will add a couple of lines explaining the plots too. Still WIP. Will update tomorrow.

Why isn't it one neuron with two input channels? How are you going to represent this in uCode? I don't think a neuron (the one receiving rewards) can access another neuron's (the one processing feedforward input from the learning synapse) y variables.

2022-10-19 00:09 UTC, awintel commented
> > > @awintel
> > > Fixed some of the text issues that was mentioned in your comment. Still working on polishing it further. But here are the answers to some of your questions.
> > > 
> > > 1. Loihi2SimCfg has not been implemented yet. I think that needs to be updated. I can work on fixing that.
> > > 2. Yes, the idea of using two post-synaptic neurons is to change the reward trace for each neuron and show that the modulation of the plastic synapse is dependent on the reward signal. It will be evident once I include the output plot. I will add a couple of lines explaining the plots too. Still WIP. Will update tomorrow.
> > 
> > 
> > Why isn't it one neuron with two input channels? How are you going to represent this in uCode? I don't think a neuron (the one receiving rewards) can access another neuron's (the one processing feedforward input from the learning synapse) y variables.
> 
> Each post-synaptic neuron does have 2 inputs -- a standard, FF spiking input as would be required by 2 factor STDP, and a graded reward input. It is important to show a network with 2 post-synaptic neurons because we are demonstrating that the magnitude and timing of the post-synaptic reward traces can be driven heterogeneously by synaptic inputs and vary across neurons. This capability, enabled by ucode, is what distinguishes Loihi 2 learning behavior from Loihi 1 learning behavior, in which we could only globally broadcast a single reward signal to the entire neural population. We've highlighted this new Loihi 2 learning feature in press releases, so I think it's important and valuable to demonstrate support for it in Lava here. It's also analogous to use cases Garrick has spoken to in Loihi deep dive presentations and is definitely implementable in ucode. (There is no dependence/communication between neurons happening.) I'm refining the tutorial text this evening to clearly communicate these features.

Maybe it's just a terminology issue that I don't understand... You are also saying that a single post synaptic neuron has two DA inputs for feedforward and reward input targeting a specific post synaptic neuron. From this post synaptic neuron, the reward will be sent back to all feedforward synapses terminating to that neuron.
I don't see where a second post-synaptic neuron would come in. If you truly have two independent post synaptic neurons, then you will have trouble getting the reward received by one neuron to the feedforward synapses of the other neuron. 
Are you just calling the two DAs of that single post-synaptic neuron "a neuron"?

2022-10-24 16:04 UTC, tim-shea reviewed
Have not gotten to do in depth review of the tutorials yet, but overall this looks well structured.

2022-10-24 16:19 UTC, bala-git9 commented on src/lava/proc/learning_rules/r_stdp_learning_rule.py
> +    def __init__(
Done

2022-10-24 19:53 UTC, bala-git9 commented on src/lava/proc/learning_rules/r_stdp_learning_rule.py
> +            eligibility_trace_decay_tau: str,
Well, the Learning Engine API accepts literals in the form 2^y or x*2^y. If we don't want to do mantissa + exponent format, I can change the r_stdp_learning_rule wrapper to accept a float value and convert it to Loihi-specific literal form.

2022-10-25 02:33 UTC, bala-git9 commented on src/lava/magma/core/model/py/connection.py
> +class PlasticConnection:
Done

2022-10-25 02:33 UTC, bala-git9 commented on src/lava/magma/core/model/py/connection.py
>      """Fixed-point, bit-approximate implementation of the Connection base
Done

2022-10-25 02:34 UTC, bala-git9 commented on src/lava/magma/core/model/py/neuron.py
> +class PlasticNeuronModel(PyLoihiProcessModel):
Done

2022-10-25 02:35 UTC, bala-git9 commented on src/lava/proc/dense/process.py
Fixed it

2022-10-25 02:36 UTC, bala-git9 commented on src/lava/proc/learning_rules/three_factor_learning_rules.py
> +    def __init__(
This seems like was a duplicate, will remove this.

2022-10-25 16:28 UTC, tim-shea commented on src/lava/proc/learning_rules/r_stdp_learning_rule.py
> +            eligibility_trace_decay_tau: str,
Yes, the second option would be preferred. A user would likely want to specify the decay as a float literal, yet be able to see in the docstring how that will be realized with limited precision, if they care about such things.

2022-10-25 16:37 UTC, bala-git9 commented on src/lava/proc/learning_rules/r_stdp_learning_rule.py
> +            eligibility_trace_decay_tau: str,
Done

2022-10-25 16:51 UTC, tim-shea approved these changes
Changing comment to approve. Previous suggestions could be addressed in a second iteration in v0.6.

2022-10-25 16:58 UTC, weidel-p commented on src/lava/magma/core/model/py/connection.py
> +    s_in_y3 = None
I completely agree, but it's difficult. These names are deeply buried in the way the learning engine works. So, for example the strings defining the weight changes use these names. (i.e. "dw = 2 * x0 * y1 - 3 * y0 * x1"). To change that here would introduce inconsistencies or additional complexity in the parser. Moreover, these variable can have different meaning. In hard-coded neurons these are always low-pass filtered spike trains, but in UC neurons those are arbitrary. So finding a meaningful name for them is difficult.

We mitigated this issue by introducing a high level description of learning rules exposing parameters with meaningful names which are internally translated to x1, y1, etc. (see the STDP learning rule or the RewardModulatedSTDP learning rule)

2022-10-25 17:11 UTC, weidel-p commented on src/lava/magma/core/process/connection.py
>      """Base class for connection Processes.
We can work a bit on the naming and the docstrings, but the `LearningConnectionProcess` is needed mix in the learning related features on the `Process` level and the `LearningConnection` is needed on the `ProcessModel` level. It's true, `Dense` etc do not have `Process` in their name, but `AbstractProcess` has. We added a `Process` in the name to indicate that this has to be mixed into `Processes` not `ProcessModels`.

2022-10-25 17:17 UTC, weidel-p commented on src/lava/proc/dense/process.py
>      """Dense connections between neurons. Realizes the following abstract
Yes, ideally we would implement that using a composition, but ran into bigger problems when we tried. The other option is to not inherit from a `LearningConnectionProcess` base class at all and expose all the complexity to the process library, which would not be nice. I prefer to keep this solution. Also multiple inheritance is already used in Lava in other places.

2022-10-25 20:46 UTC, awintel approved these changes
Looks better but still there are a couple of "cosmetic" things you should improve:
(Will approve nonetheless to not hold up the merge once you've addressed these)

- Please check all your headlines again. There are still several examples with random lower/upper case spelling like: "Initialize Network Processes", "Connect network Processes", "Tag Dynamics for Post-synaptic Neurons", "Reward Trace for Post-synaptic Neurons"
- "...how the improved Lava learning API..." -> "improved" is out of context. "Improved" over what?
- There is no hyphen between Loihi and 2. Sometimes you also say Loihi2 without white space.
- The intro paragraph doesn't seem accurate or maybe is outdated with the code: "... first define interface for RSTDP". I don't see an interface definition. You only instantiate a pre-build rule and build a network to use it. Only in the very end you define a custom rule.
- I would pull the note about Loihi 2 unavailability into an emphasis box. This way it's clearer that this is temporary and also reduces the chance that we forget to update the text once the code changes.
- Wrong string before the definition of your post neurons: "# Pre-synaptic neuron parameters"
- Although I now understand why there are two post neurons based on our discussion. The reader of this tutorial has no idea at this point of the tutorial why you chose two. Please motivate why there are two not just state that there are two. It's because you want to demonstrate something specific in the end.
- Could you align the x axis of the spike and trace plots?
- As pointed out in my last review, I feel the tutorial would benefit from at least a minimal explanation/discussion of the final results. You show one figure after the other but what should the reader take note of?
- Is this correct: "FrÃƒÂ©maux"? Looks messed up.
- Is there now way around exposing the name LoihiUCLearningRule at the user level that should be agnostic of HW details? This is unfortunate...

2022-10-26 07:10 UTC, gkarray approved these changes
Looks good overall.
Left comments on minor things, but will approve nonetheless to not hold up the release. If these can be addressed now, good, otherwise, they can be left for a future release.

One final comment : 
- I think the folder `src/lava/proc/learning_rules` shouldn't go in the `proc` library at all. It does not contain any Process definition. This folder should probably instead be moved to `src/lava/magma/core/learning/learning_rules`

2022-10-26 09:32 UTC, weidel-p commented on src/lava/magma/core/model/py/connection.py
> +        self._update_trace_randoms()
agreed. It's also not necessary to call super() here. I changed the function name to `recv_traces`.

2022-10-26 09:32 UTC, weidel-p commented on src/lava/proc/dense/models.py
> +        super().run_spk(s_in)
see above

2022-10-26 09:32 UTC, weidel-p commented on src/lava/proc/dense/models.py
> +        super().run_spk(s_in)
see above

2022-10-26 15:08 UTC, weidel-p commented
Regarding the correct place for the high level learning rules such as STDP. Strictly speaking, @gkarray is correct, they are not Processes, so they should be somewhere else. But in my opinion, they should stay in the process library as this is the place where a user is looking for commonly used models such as LIF. Our high level implementations of learning rules serve the same purpose. Additionally, I would like to avoid imports from deep inside lava for common use-cases.

2022-10-27 08:46 UTC, merged