Revert "Compiler graph: Enable model selection, fixing warning in QUB…
lava-nc/lava pull request #419
Opened 2022-10-14 22:57 UTC by mathisrichter

…O tutorial (#418)"

This reverts commit bafca331201847e3b94a821be3d563574c674eda.

Issue Number: 

Objective of pull request: Reverting a commit because the changes to the discovery of ProcModels breaks multiple unit tests in lava-on-loihi.

## Pull request checklist

Your PR fulfills the following requirements:
- [ ] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
- [ ] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
- [ ] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
- [ ] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
- [ ] Build tests (`pytest`) passes locally

## Pull request type

 

 

Please check your PR type:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe): 

## What is the current behavior?

-

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Supplemental information

2022-10-14 23:31 UTC, bamsumit approved these changes

2022-10-14 23:49 UTC, mathisrichter commented
I am getting a unit test failure in lava-on-loihi of the test `test_compile_proc_groups`. I think this should be unrelated to this PR but needs to be looked into.

2022-10-17 08:44 UTC, phstratmann requested changes
Hi Mathis,
Thanks for taking care of this!
However, I would ask you to just revert the change in compiler_graphs.py.
The other changes (unit tests, tutorial) do not break anything, and better code practice, and will be required to ensure that the unit tests will still work once we do fix the compiler. Thus, could you leave the changes in test_models, test_monitors, and the tutorial?
Thanks!

2022-10-20 17:43 UTC, phstratmann approved these changes

2022-10-20 20:26 UTC, merged