grpc_draft
lava-nc/lava pull request #426
Opened 2022-10-17 08:43 UTC by szc321

Issue Number: 

Objective of pull request:

## Pull request checklist

Your PR fulfills the following requirements:
- [ ] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
- [ ] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
- [ ] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
- [ ] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
- [ ] Build tests (`pytest`) passes locally

## Pull request type

 

 

Please check your PR type:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe): 

## What is the current behavior?

-

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Supplemental information

2022-10-21 07:26 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/test/test_channel.py
> +        socket_channel = Channel(
Create new ut for grpc channel. Do not reuse socketchannel.

2022-10-21 07:26 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc.h
> +friend GrpcManager &GetGrpcManager();
use space ahead.

2022-10-21 07:26 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc.h
> +    urls_.push_back(url);
code style. use space before and after + ......

2022-10-21 07:26 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_port.cc
> +}  // namespace message_infrastructure
blank space at last line.

2022-10-21 07:26 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_port.cc
> +#include "message_infrastructure/csrc/channel/grpc/build/grpcchannel.grpc.pb.h"
Use same style for header files.

2022-10-24 06:45 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/socket/socket_channel.cc
> +
rm useless blank line.

2022-10-24 06:45 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc.h
> +#include <set>
rm useless headers.

2022-10-24 06:45 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_port.cc
> +  recvqueue = std::make_shared<RecvQueue<GrpcMetaDataPtr>>(name_, size_, nbytes_); //NOLINT
Delete //nolint comment.

2022-10-24 06:45 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_port.cc
> +                 :AbstractRecvPort(name, size, nbytes), done_(false), url_(url) { //NOLINT
Delete //NOLINT comment.

2022-10-24 06:45 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_port.cc
> +  char* data = (char*)metadata->mdata; //NOLINT
Delete NOLINT comment and fix lint error.

2022-10-24 06:45 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_port.cc
> +  //}
Remove useless code.

2022-10-24 06:45 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/shmem/shmem_port.h
> +/*
Remove useless code

2022-10-24 06:45 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/core/common.h
> +  explicit RecvQueue(const std::string& name,
Constructor functions with more than 1 paramters do not need to use 'explicit'.

2022-10-24 06:45 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/test/test_channel.py
> +    unittest.main()
use $flakeheaven lint src/lava tests/ to check python file lint errors.

2022-10-24 09:26 UTC, killight98 requested changes

2022-10-24 09:26 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_port.h
> +  std::atomic_bool done_;
useless value?

2022-10-24 09:26 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_channel.h
> +              const size_t &nbytes);
remove nbytes

2022-10-24 09:26 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_port.cc
> +  void* data = malloc(nbytes_);
calculate nbytes_ by elsize and type...

2022-10-24 09:26 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_port.cc
> +  grpcdata.set_value(data, nbytes_);
same with `GrpcRecvPort::GrpcMetaData2MetaData`

2022-10-25 09:09 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_channel.cc
> +    std::cout << "url is used" << std::endl;
Print a log.

2022-10-25 09:09 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_port.h
> +  std::shared_ptr<Channel> channel;
Code style. `channel_`.

2022-10-26 02:50 UTC, szc321 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/ports.py
> +from MessageInfrastructurePywrapper import GetRPCChannel as CppRPCChannel
If I delete this, there is a  ImportError: cannot import name 'GetRPCChannel' from 'message_infrastructure.ports' (/home/szc/LAVA/lava_nc_grpc_szc/lava/src/lava/magma/runtime/message_infrastructure/message_infrastructure/ports.py)

2022-10-26 02:55 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/core/channel_factory.h
> +}
Position of `}`

2022-10-26 02:55 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/core/channel_factory.h
> +}
Position of `}`

2022-10-26 02:55 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc.h
> +    urls_.push_back(url);
use 1 container to store the urls for both AllocURL and CheckURL.

2022-10-26 07:31 UTC, hexu33 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc.h
> +  std::string AllocURL() {
`AllocURL` should also check url first.

2022-10-28 11:01 UTC, merged