enhancement of data convertion at grpc channel
lava-nc/lava pull request #479
Opened 2022-11-11 06:51 UTC by szc321

Issue Number: 

Objective of pull request:

## Pull request checklist

Your PR fulfills the following requirements:
- [ ] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
- [ ] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
- [ ] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
- [ ] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
- [ ] Build tests (`pytest`) passes locally

## Pull request type

 

 

Please check your PR type:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe): 

## What is the current behavior?

-

## What is the new behavior?

-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Supplemental information

2022-11-11 06:56 UTC, szc321 commented
the GrpcSendPortProxy can't inherit the SendPortProxy, because the send_port_  between the two Class is different.

2022-11-14 07:52 UTC, killight98 requested changes

2022-11-14 07:52 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/port_proxy.cc
> +  } else {
remove else.

2022-11-14 07:52 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/test/CMakeLists.txt
> +
remove useless change

2022-11-14 07:52 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/port_proxy.cc
> +  // auto dtype = PyArray_Type(array);  // no work
remove useless code

2022-11-14 07:52 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/test/cpptest/test_ddschannel.cc
> +  int loop = 1000;
restore loop value

2022-11-14 07:52 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/test/cpptest/test_grpc_delivery.cc
> +    printf("result: %ld\n", result);
useless?

2022-11-14 07:52 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/test/test_all_delivery.py
> +class TestDelivery(unittest.TestCase):
need to change ut func name?

2022-11-14 07:52 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel_proxy.cc
> +                                                   channel_->GetSendPort());
code style

2022-11-14 07:52 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel/grpc/grpc_port.cc
> -GrpcMetaData MetaData2GrpcMetaData(MetaDataPtr metadata) {
creare an inline func at grpc_port.h?
we could call this func at cpp ut.

2022-11-14 07:52 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/message_infrastructure/csrc/channel_proxy.cc
> +                                                   channel_->GetSendPort());
code style

2022-11-14 08:00 UTC, szc321 commented on src/lava/magma/runtime/message_infrastructure/test/test_all_delivery.py
> +class TestDelivery(unittest.TestCase):
change to TestAllDelivery

2022-11-14 10:45 UTC, killight98 approved these changes

2022-11-14 11:29 UTC, merged