Bugfix to enable monitoring aliased vars
lava-nc/lava pull request #675
Opened 2023-04-27 13:49 UTC by AlessandroPierro

Issue Number: #676 

Objective of pull request:

## Pull request checklist

Your PR fulfills the following requirements:
- [x] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
- [ ] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
- [ ] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
- [x] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
- [x] Build tests (`pytest`) passes locally

## Pull request type

 

 

Please check your PR type:

- [x] Bugfix

## What is the current behavior?

- An assertion was raised when it was requested to create two different implicit var ports with the same name on the same process

## What is the new behavior?

- The different var ports will be created without assertion, with a numerical suffix added to the name

## Does this introduce a breaking change?

- [x] No

2023-04-27 14:21 UTC, AlessandroPierro commented
Required to merge: https://github.com/lava-nc/lava-optimization/pull/217

2023-04-27 14:56 UTC, PhilippPlank approved these changes

2023-04-28 12:20 UTC, weidel-p requested changes
This PR adds a suffix to a port name if it already exists which is an easy solution to the problem described in the issue.

I have one request though, could you please add a test which shows that the original issue is solved? So that we can probe aliased vars?

2023-04-28 12:20 UTC, weidel-p commented on src/lava/magma/core/process/ports/ports.py
> +                found_unique_name = False
could we write that a bit more elegantly? 

Maybe something like:
```
name_suffix = 0
while hasattr(var.process, vp.name):
    vp.name += str(name_suffix)
    name_suffix += 1
```

2023-05-02 07:24 UTC, weidel-p approved these changes

2023-05-02 08:39 UTC, merged