Fix the performance issue
lava-nc/lava pull request #705
Opened 2023-05-29 09:11 UTC by szc321

Issue Number: 

Objective of pull request:

## Pull request checklist

Your PR fulfills the following requirements:
-   [ ] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
-   [ ] Tests are part of the PR (for bug fixes / features)
-   [ ] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
-   [ ] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
-   [ ] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
-   [ ] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
-   [ ] Build tests (`pytest`) passes locally

## Pull request type

 

 

Please check your PR type:

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Code style update (formatting, renaming)
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Build related changes
-   [ ] Documentation changes
-   [ ] Other (please describe): 

## What is the current behavior?

-

## What is the new behavior?

-

## Does this introduce a breaking change?

-   [ ] Yes
-   [ ] No

## Supplemental information

2023-05-31 07:06 UTC, hexu33 commented on src/lava/magma/runtime/_c_message_infrastructure/csrc/message_infrastructure_py_wrapper.cc
> +  .def(py::init<>())
Modify code indentation

2023-05-31 07:06 UTC, hexu33 commented on src/lava/magma/runtime/_c_message_infrastructure/csrc/port_proxy.cc
> +                      py::function>> *channel_actions,
Modify code indentation

2023-05-31 07:06 UTC, hexu33 commented on src/lava/magma/runtime/_c_message_infrastructure/csrc/port_proxy.cc
> +    while (true) {
Modify code indentation

2023-05-31 07:06 UTC, hexu33 commented on src/lava/magma/runtime/_c_message_infrastructure/csrc/port_proxy.cc
> +    std::unique_lock<std::mutex> lock(cv_mutex_);
Modify code indentation

2023-05-31 07:06 UTC, hexu33 commented on src/lava/magma/runtime/_c_message_infrastructure/csrc/port_proxy.h
> +  void Set_observer(std::function<void()> obs);
Follow func name rule.

2023-05-31 07:06 UTC, hexu33 commented on src/lava/magma/runtime/_c_message_infrastructure/csrc/port_proxy.h
> +  void Set_observer(std::vector<std::tuple<RecvPortProxyPtr,
Follow func name rule.

2023-05-31 10:09 UTC, killight98 requested changes

2023-05-31 10:09 UTC, killight98 commented on src/lava/magma/runtime/message_infrastructure/ports.py
> +class Selector(CPPSelector):
move it into `__init__.py` as following:
```py
from lava.magma.runtime.message_infrastructure.MessageInfrastructurePywrapper \
    import CPPSelector as Selector
```

2023-05-31 10:09 UTC, killight98 commented on src/lava/magma/runtime/_c_message_infrastructure/csrc/port_proxy.cc
> +  recv_port_->obs_lk_.lock();
replace by [`std::lock_guard`](https://en.cppreference.com/w/cpp/thread/lock_guard)

2023-06-01 11:09 UTC, killight98 requested changes

2023-06-01 11:09 UTC, killight98 commented on src/lava/magma/runtime/_c_message_infrastructure/csrc/channel/shmem/shmem_port.cc
> +      bool not_empty = recv_queue_->Probe();
useless?

2023-06-01 11:09 UTC, killight98 commented on src/lava/magma/runtime/_c_message_infrastructure/csrc/port_proxy.h
> +  void SetObserver(std::function<void()> obs);
useless?

2023-06-02 07:54 UTC, killight98 approved these changes

2023-06-02 07:55 UTC, merged