CLP Tutorial 01
lava-nc/lava pull request #721
Opened 2023-06-20 21:53 UTC by elvinhajizada

Issue Number: 
#706 

Objective of pull request:
Create the first tutorial on the initial version of CLP (Continually Learning Prototypes) algorithm, explaining how to set up and use the CLP processes from #706 
## Pull request checklist

Your PR fulfills the following requirements:
-   [x] [Issue](https://github.com/lava-nc/lava/issues) created that explains the change and why it's needed
-   [ ] Tests are part of the PR (for bug fixes / features)
-   [ ] [Docs](https://github.com/lava-nc/docs) reviewed and added / updated if needed (for bug fixes / features)
-   [x] PR conforms to [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions)
-   [x] [PR applys BSD 3-clause or LGPL2.1+ Licenses](https://lava-nc.org/developer_guide.html#add-a-license) to all code files
-   [x] Lint (`flakeheaven lint src/lava tests/`) and (`bandit -r src/lava/.`) pass locally
-   [x] Build tests (`pytest`) passes locally

## Pull request type

 

 

Please check your PR type:

-   [ ] Bugfix
-   [x] Feature
-   [ ] Code style update (formatting, renaming)
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Build related changes
-   [ ] Documentation changes
-   [ ] Other (please describe): 

## What is the current behavior?

- No CLP tutorial

## What is the new behavior?

- The first CLP tutorial, describing the basics on the synthetic data

## Does this introduce a breaking change?

-   [ ] Yes
-   [x] No

## Supplemental information

2023-06-20 21:56 UTC, elvinhajizada commented
**Please ignore everything except the new tutorial notebook **

2023-07-19 15:28 UTC, weidel-p commented
I will review that in more detail, but I already saw some minor things you could change.
1. images should not go in this repository directly but should go here: https://github.com/lava-nc/lava-nc.github.io/tree/main/_static/images . This is to avoid the lava repository growing bigger.
2. Your tutorials are called tutorial01 and tutorial03. Is there a tutorial02 still coming? Otherwise relabel.

2023-07-20 10:42 UTC, weidel-p commented
I added comments to the first tutorial and started a PR to your branch. https://github.com/elvinhajizada/lava/pull/1

2023-07-21 11:00 UTC, PhilippPlank requested changes
Please add/fix all licensing headers and as PW said, the images should not be added directly to this repository. Some minor remarks besides that.

2023-07-24 19:16 UTC, weidel-p approved these changes

2023-07-24 21:19 UTC, PhilippPlank commented
Tutorials use sklearn module, which is currently not part of lava.

2023-09-18 09:46 UTC, elvinhajizada commented
The significant update to this PR includes:

- New CLP experiments are devised to test different aspects of the algorithm
- The abstract CLP class is improved to facilitate these experiments
- The user is given two options: use pre-extracted features or extracts features on your own (if you have torch & torchvision)
- Torch and torchvision dependencies are optional and if not there, code will use pre-extracted features
- Scikit-learn dependency is added and will be added to Lava requirements for the next release

2023-09-18 10:56 UTC, elvinhajizada commented
The tests for CLP tutorials are commented out temporarily, till sk-learn is added to CI. Once that happens, I will add these tests before merge

2023-09-21 12:58 UTC, merged